version: '2.13'
services:
  app:
    build: 
      context: .
    volumes:
      - .:/pension-plus
    ports:
      - 3000:3000
    image: app:react
    container_name: react-container
    command: npm start